pipeline:
    restore-cache:
      image: drillster/drone-volume-cache
      restore: true
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache

    build:
      image: node:6.7.0
      commands:
        - npm install
        - npm run build

   rebuild-cache:
      image: drillster/drone-volume-cache
      rebuild: true
      mount:
        - ./node_modules
      volumes:
        - /tmp/cache:/cache
    #publish:
    #  docker:
    #    registry: quay.io
    #    file: Dockerfile
    #    when:
    #      event: tag
    #deploy:
    #  rancher:
    #    url: $$R_URL
    #    when:
    #      event: tag
