pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node
    commands:
      - npm install
      - npm build


  publish:
    image: plugins/docker
    registry: quay.io
    username: ${QUAY_USERNAME}
    password: ${QUAY_PASSWORD}
    email: ${QUAY_EMAIL}
    repo: ${QUAY_REPO}
    file: Dockerfile

  deploy:
    image: peloton/drone-rancher
    url: ${R_URL}
    access_key: ${R_ACC}
    secret_key: ${R_SEC}
    service: hello/hello
    docker_image: ${QUAY_REPO}

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

